#!/usr/bin/env bash

if
  [[ -s "/home/quirky/.rvm/gems/ruby-2.3.3@global/environment" ]]
then
  source "/home/quirky/.rvm/gems/ruby-2.3.3@global/environment"
  exec rake "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/quirky/.rvm/gems/ruby-2.3.3@global/environment'" >&2
  exit 1
fi
